export const GbaTitles = [
  '001 Pokemon Emerald Version.gba',
  '002 Pokemon Ruby.gba',
  '003 Pokemon Saphire.gba',
  '004 Pokemon Fire Red.gba',
  '005 Pokemon Leaf Green.gba',
  '006 Pokemon Mystery Dungeon-Red Rescue Team.gba',
  '019 Golden Sun.gba',
  '020 Tekken Advance.gba',
  '021 Crash Bandicoot.gba',
  '022 Crash Bandicoot 2.gba',
  '023 Crash Nitro Kart.gba',
  '024 Crash Bandicoot Fusion.gba',
  '025 Crash of the Titans.gba',
  '026 Donkey Kong Country 1.gba',
  '027 Donkey Kong Country 2.gba',
  '028 Donkey Kong Country 3.gba',
  '029 Sonic Advance.gba',
  '030 Sonic Advance 2.gba',
  '031 Sonic Advance 3.gba',
  '032 Sonic Battle.gba',
  '033 Rayman Advance.gba',
  '034 Rayman-Hoodlums Revenge.gba',
  '035 Rayman Raving Rabbits.gba',
  '036 Rayman 3.gba',
  '037 The King Of Fighters EX1.gba',
  '038 The king of the fighter EX2.gba',
  '039 Metal Slug Advance.gba',
  '040 Dragon Ball-Ad Adv.gba',
  '041 Kirby Nightmare In Dreamland.gba',
  '042 Kirby And The Amazing Mirror.gba',
  '043 Driv3r.gba',
  '044 Spyro-Season of Ice.gba',
  '045 Spyro 2-Season Of Flame.gba',
  '046 Spyro-Attack of the Rhynocs.gba',
  '047 Spyro Orange the Cortex Conspiracy.gba',
  '048 The Legend of Spyro-The Eternal Night.gba',
  '049 The Legend of Spyro - A New Beginning.gba',
  '050 World Soccer Winning 11.gba',
  '052 CT Special Forces.gba',
  '053 CT Special Forces 2.gba',
  '054 Contra Advance.gba',
  '055 Final Fantasy I & II-Dawn of Souls.gba',
  '056 Final Fantasy Tactics Advance.gba',
  '057 Final Fantasy IV.gba',
  '058 Final Fantasy V.gba',
  '059 Final Fantasy VI.gba',
  '060 Wario Land 4.gba',
  '061 Wario Ware Inc.gba',
  '062 Wario Ware Twisted!.gba',
  '063 Yggdra Union.gba',
  '064 Mortal Kombat Advance.gba',
  '065 Mortal Kombat Deadly Alliance.gba',
  '066 Mortal Kombat Tournament Edition.gba',
  '067 Megaman Zero 1.gba',
  '068 Megaman Zero 2.gba',
  '069 Megaman Zero 3.gba',
  '070 Megaman Zero 4.gba',
  '071 MegaMan & Bass.gba',
  '072 Harvest Moon-Mineral Town.gba',
  '073 Harvest Moon-More Friends of Mineral Town.gba',
  '074 Fire Emblem-The Sacred Stones.gba',
  '075 Fire Emblem.gba',
  '076 Super street fighter II turbo-revival.gba',
  '077 Street Fighter Alpha 3.gba',
  '078 Super Puzzle Fighter II.gba',
  '079 Castlevania-Circle of the Moon.gba',
  '080 Castlevania-Harmony Of Dissonance.gba',
  '081 Castlevania-Aria Of Sorrow.gba',
  '082 The Legend Of Zelda-Link To The Past.gba',
  '083 The Legend of Zelda-The Minish Cap.gba',
  '084 Shining Soul.gba',
  '085 Shining Soul II.gba',
  '086 Metroid Zero Mission.gba',
  '087 Metroid Fusion.gba',
  "088 Spiderman-Mysterio's Menace.gba",
  '089 Spider-Man 2.gba',
  '090 Spider-Man 3.gba',
  '091 Spider-Man-The Movie.gba',
  '092 Ultimate Spider-Man.gba',
  '093 Spider-Man-Battle For New York.gba',
  '094 Teenage mutant ninja turtles.gba',
  '095 Teenage Mutant Ninja Turtles 2.gba',
  '096 TMNT.gba',
  '097 The Urbz-Sims in the city.gba',
  '098 The Sims 2.gba',
  '099 Monster Rancher Advance 1.gba',
  '100 Monster Rancher Advance 2.gba',
  '101 Super Robot Taisen OG 1.gba',
  '102 Super Robot Taisen OG 2.gba',
  "103 Harry Potter and the Sorcerer's Stone.gba",
  '104 Harry Potter and The Chamber of Secrets.gba',
  '105 Harry Potter and the Prisoner of Azkaban.gba',
  '106 Harry Potter and the Goblet of Fire.gba',
  '107 Harry Potter and the Order of the Phoenix.gba',
  '108 American Idol.gba',
  '109 Bionicle Heroes.gba',
  "110 Charlotte's Web.gba",
  '111 Disney Sports Football.gba',
  '112 Disney Sports Skateboarding.gba',
  '113 Disney Sports Snowboarding.gba',
  '114 Dogz 2.gba',
  '115 Duel Masters-Shadow of the Code.gba',
  '116 Dynasty Warriors Advance.gba',
  '117 Eragon.gba',
  '119 Hamtaro Ham Ham Games.gba',
  '120 Hamtaro Rainbow Rescue.gba',
  "121 High School Musical-Livin' the Dream.gba",
  '122 Ice Age 2-The Meltdown.gba',
  '123 Juka and the monophonic menace.gba',
  '124 Lego Star Wars 2.gba',
  '125 LEGO Star Wars-The Video Game.gba',
  "126 Lemony Snicket's A Series of Unfortunate Events.gba",
  '127 Lord of the Rings-The Return of the King.gba',
  '128 Lord Of The Rings-The Two Towers.gba',
  '129 Medal of Honor Infiltrator.gba',
  '130 My Animal Centre in Africa.gba',
  '131 Pirates of the Caribbean 2-Dead Mans Chest.gba',
  "132 Dexter's Laboratory-Chess Challenge.gba",
  '133 Garfield-The Search for Pooky.gba',
  '134 Ice Nine.gba',
  '135 Mech Platoon.gba',
  "136 Oddworld-Munch's Oddysee.gba",
  '137 Power Pro Kun Pocket 4.gba',
  '138 Robots.gba',
  '139 Scurge-Hive.gba',
  '140 Shaman King-Legacy of the Spirits-Soaring Hawk.gba',
  '141 Shaman King-Legacy of the Spirits-Sprinting Wolf.gba',
  '142 Shaman King-Master of Spirits 2.gba',
  '143 Summon Night-Swordcraft Story.gba',
  '144 Summon Night-Swordcraft Story 2.gba',
  '145 Superman Returns-Fortress of Solitude.gba',
  '146 Sword of Mana.gba',
  '147 The Chronicles of Narnia.gba',
  '148 The Lord of the Rings-The Third Age.gba',
  '149 The Sims Bustin Out.gba',
  '150 Tron 2.0-Killer App.gba',
  '151 Ultimate Muscle-The Path of the Superhero.gba',
  '152 WinX Club.gba',
  '153 Acing Gears Advance.gba',
  '154 Advance GTA.gba',
  '155 Advance Guardian Heroes.gba',
  '156 Asterix & Obelix PAF! Them All!.gba',
  '157 Astro Boy.gba',
  '158 Atomic Betty.gba',
  '159 Avatar-The LastAirbender.gba',
  '160 Ballistic-Ecks vs Sever.gba',
  '161 Barnyard.gba',
  '162 Batman Vengeance.gba',
  '163 Best Friends-My Horse.gba',
  '164 Beyblade Vforce-Ultimate Blader Jam.gba',
  '165 Blender Bros.gba',
  '166 Bomberman Max 2 Blue.gba',
  '167 Bomberman Max 2 Red.gba',
  '168 Boxing fever.gba',
  '169 Bratz Forever Diamondz.gba',
  '170 Bratz Rock Angelz.gba',
  "171 Britney's Dance Beat.gba",
  '172 Broken Sword-The Shadow of the Templars.gba',
  '173 Bruce Lee Return of the Legend Vivendi Universal.gba',
  "174 Cabela's big game hunter.gba",
  '175 Catwoman.gba',
  '176 Charlie And The Chocolate Factory.gba',
  '177 CIMA The Enemy.gba',
  '178 Columns Crown.gba',
  '179 Crazy Taxi-Catch A Ride.gba',
  '180 Crouching tiger, hidden dragon.gba',
  '181 Dark Arena.gba',
  '182 Dave mirra freestyle bmx 2.gba',
  '183 Dave mirra freestyle bmx 3.gba',
  '185 Demikids-dark version.gba',
  '186 Demikids-light version.gba',
  '187 Digimon Racing.gba',
  '188 Dinotopia-The Timestone Pirates.gba',
  '189 Disney Brother Bear.gba',
  '190 Disney Princess.gba',
  "191 Disney's American Dragon-Jake Long, Rise of the Huntsclan.gba",
  "192 Disney's Cinderella-Magical Dreams.gba",
  "193 Disney's Extreme Skate Adventure.gba",
  "194 Disney's Herbie Fully Loaded.gba",
  "195 Disney's Kim Possible.gba",
  "196 Disney's Lilo & Stitch 2-Hamsterveil Havoc.gba",
  "197 Disney's Magical Quest 3.gba",
  "198 Disney's Party.gba",
  "199 Disney's The Jungle Book 2.gba",
  '200 Disneys Lilo & Stitch.gba',
  '201 Disneys The Lion King 1.5.gba',
  '202 Dogz Fashion.gba',
  '203 Dogz.gba',
  '204 Dokapon.gba',
  '205 Donald Duck Advance.gba',
  '206 Dr. Muto.gba',
  '207 Dragon Ball GT-Transformation.gba',
  '208 Dragon Ball Z-The CollETCible Card Game.gba',
  '209 Dragon ball Z-the legacy of goku II.gba',
  '211 Dragon Tales-Dragon Adventures.gba',
  "212 DragonBall Z Buu's Fury.gba",
  '213 Dreamworks Shark Tale.gba',
  '214 Driver 2 Advance.gba',
  '215 Duel Masters-Kaijudo Showdown.gba',
  '216 Duel Masters-Sempai Legends.gba',
  '217 Earthworm Jim 2.gba',
  '218 Earthworm Jim.gba',
  '219 Ecks vs. Sever.gba',
  '220 Ed, Edd n Eddy-The Mis-Edventures.gba',
  '221 ESPN Great Outdoor Games-Bass Tournament.gba',
  '222 ESPN X-Games Skateboarding.gba',
  '223 Famista Advance.gba',
  '225 Finding Nemo.gba',
  '226 Fire pro wrestling 2.gba',
  '227 Fire pro wrestling.gba',
  '228 Flushed Away.gba',
  '229 Frogger Advance-The Great Quest.gba',
  "230 Frogger's adventures 2-the lost wand.gba",
  "231 Frogger's journey-the forgotten relic.gba",
  "232 Gekido advance-kintaro's revenge.gba",
  '233 Ghost Rider.gba',
  '234 Golden Nugget Casino.gba',
  '235 GT Advance 2 Rally Racing.gba',
  '236 GT Advanced 3 Pro Concept Racing.gba',
  '237 GT Racers.gba',
  '238 Guilty Gear X.gba',
  '239 Home On The Range.gba',
  '240 Hot Wheels Stunt Track Challenge.gba',
  '241 Hot Wheels Velocity X.gba',
  '242 Hot Wheels-World Race.gba',
  '243 International Superstar Soccer.gba',
  '244 Invader.gba',
  '245 James Bond 007 Everything or Nothing.gba',
  '246 Jonny Moseley Mad Trix.gba',
  '247 Jurassic park III - dino attack.gba',
  '248 Jurassic park III - island attack.gba',
  '249 Jurassic park III - the DNA factor.gba',
  '250 Justice League Chronicles.gba',
  '251 Justice League Heroes-The Flash.gba',
  '252 Justice League-Injustice for All.gba',
  '253 Kong The 8th Wonder of the World.gba',
  '254 Kong-The Animated Series.gba',
  '255 Land Before Time Into The Mysterious Beyond.gba',
  '256 Legends of Wrestling 2.gba',
  '257 Lego Bionicle.gba',
  '258 Lego Island 2.gba',
  '259 Lego Racers 2.gba',
  '260 LEGO Soccer Mania.gba',
  '261 Little Mermaid-Magic In Two Kingdoms.gba',
  '262 Lizzie McGuire 3-Homecoming Havoc.gba',
  '263 Looney Tunes-Back in Action.gba',
  '264 Lufia - the ruins of lore.gba',
  "265 M&M's Blast!.gba",
  '266 Madagascar-Operation Penguin.gba',
  '267 Major League Baseball 2007.gba',
  '268 Racing Gears Advance.gba',
  '269 Marvel Ultimate Alliance.gba',
  '270 Masters of the Universe HeMan-Power of Grayskull.gba',
  '271 Math Patrol-The Kleptoid Threat.gba',
  '272 Medabots AX-Metabee Version.gba',
  '273 Medabots-Rokusho Version.gba',
  '274 Medal of Honor Underground.gba',
  '275 Meet the Robinsons.gba',
  '276 Mega Man Battle Network 6-Cybeast Falzar.gba',
  '277 Mega Man Battle Network 6-Cybeast Gregar.gba',
  '278 MegaMan & Bass.gba',
  '279 Megaman Battle Chip Challenge.gba',
  '280 Megaman Battle Network 3-Blue Version.gba',
  '281 Megaman Battle Network 4-Blue Moon.gba',
  '282 Megaman Battle Network 4-Red Sun.gba',
  '283 Megaman Battle Network 5-Team Colonel.gba',
  '284 Megaman Battle Network 5-Team Protoman.gba',
  '285 Megaman Battle Network EXE 1.gba',
  '286 Megaman Battle Network EXE 2.gba',
  '287 Megaman Network Battle 3-White Version.gba',
  '288 Rockman EXE 4.5-Real Operation.gba',
  '289 Monster Jam-Maximum Destruction.gba',
  '290 Need for Speed Underground 2.gba',
  '291 No Rules Get Phat.gba',
  '292 Onimusha tactics.gba',
  '293 Open Season.gba',
  '294 Over the Hedge.gba',
  '295 Over the Hedge2-Hammy Goes.gba',
  '296 Robopon 2-Cross Version.gba',
  '297 Paws & Claws-Dogs & Cats Best Friend.gba',
  '298 Peter Pan-Return to Neverland.gba',
  '299 Petz Vet.gba',
  '300 Petz-Hamsterz Life.gba',
  '301 Pferd And Pony Mein Gestut.gba',
  '302 Phil of the Future.gba',
  "303 Piglet's Big Game.gba",
  '304 Pinball Of The Dead.gba',
  '305 Pirates of the Caribbean.gba',
  '306 Pocket Dogs.gba',
  '307 Punch King.gba',
  '308 Rainbow Six Rogue Spear.gba',
  '309 Ratatouille.gba',
  '310 Rave Master-Special Attack Force.gba',
  '311 Recca no honoo - the game.gba',
  '312 Rocky.gba',
  '313 Samurai deeper kyo.gba',
  '314 Samurai Jack-The Amulet of Time.gba',
  '315 Scooby Doo 2-Monster Unleashed.gba',
  '316 Scrabble.gba',
  '317 SD gundam force.gba',
  '318 Shaun Palmers Pro Snowboarder.gba',
  '319 Shrek 2-Beg for Mercy.gba',
  '320 Shrek 2.gba',
  '322 Shrek Super Slam.gba',
  '323 Shrek the Third.gba',
  '324 Shrek-Reekin Havoc.gba',
  '325 Shrek-Swamp Kart Speedway.gba',
  '326 Sonic Pinball Party.gba',
  "327 Space channel 5 - ulala's cosmic attack.gba",
  '328 Gunstar Super Heroes.gba',
  '329 SpongeBob Square Pants-Revenge of The Flying Dutchman.gba',
  '330 SpongeBob SquarePants-Battle for Bikini Bottom.gba',
  '331 SpongeBob Squarepants-Creature from the Krusty Krab.gba',
  '332 SpongeBob SquarePants-The Movie.gba',
  '333 Spy Hunter.gba',
  '334 Spy Kids 3D.gba',
  '336 Star Wars Episode II-Attack Of The Clones.gba',
  '337 Star Wars Episode III-Revenge of the Sith.gba',
  '338 Star Wars Trilogy-Apprentice of the Force.gba',
  '339 Star Wars-Jedi Power Battles.gba',
  '340 Strawberry Shortcake Ice Cream Island Riding Camp.gba',
  '342 Superman-Countdown to Apokolips.gba',
  "343 Surf's Up.gba",
  '344 Taiketsu! ultra hero.gba',
  '345 Tak 2-The Staff of Dreams.gba',
  '346 Tak and the Power of JuJu.gba',
  '347 Tarzan Return to the Jungle.gba',
  '349 Terminator 3 Rise Of The Machines.gba',
  '350 The Barbie Diaries High School Mystery.gba',
  '351 The Cheetah Girls.gba',
  '352 The Grim Adventures of Billy and Mandy.gba',
  '353 The Hobbit.gba',
  '354 The Incredible Hulk.gba',
  '355 The Incredibles Rise Of The Underminer.gba',
  '356 The Incredibles-rise of the underminer.gba',
  '357 The Incredibles.gba',
  '358 The Jungle Book.gba',
  '359 The Koala Brothers-Outback Adventures.gba',
  '360 The Lord of The Rings-The Fellowship Of The Ring.gba',
  '361 The Pink Panther.gba',
  '362 The Powerpuff Girls-Him and Seek.gba',
  '363 The Revenge of Shinobi.gba',
  '364 The Santa Clause 3-The Escape Clause.gba',
  '365 The Simpsons-Road Rage.gba',
  '366 The Sum of All Fears.gba',
  '367 The Tower SP.gba',
  '368 The Wild.gba',
  '369 Thunderbirds-International Rescue.gba',
  '370 Tiger Woods PGA Tour Golf.gba',
  '371 Tom and Jerry Tales.gba',
  '372 Tom and Jerry-Magic Ring.gba',
  "373 Tom Clancy's Splinter Cell.gba",
  "374 Tony Hawk's American Sk8land.gba",
  "375 Tony Hawk's Pro Skater 4.gba",
  '376 Tony Hawks Underground 1.gba',
  '377 Tony Hawks Underground 2.gba',
  '378 Totally Spies 1.gba',
  '379 Totally Spies 2 Undercover.gba',
  '380 Trollz Hair Affair.gba',
  '381 Ty the Tasmanian Tiger 2-Bush Rescue.gba',
  '382 Ty the Tasmanian Tiger 3.gba',
  '383 Virtua tennis.gba',
  '384 Wakeboarding Unleashed.gba',
  '385 Wings.gba',
  '386 Winx Club Quest for the Codex.gba',
  '387 Witch.gba',
  '388 Wolfenstein 3D.gba',
  '389 Word Safari-The Friendship Totems.gba',
  '390 X-Men 2-Wolverines Revenge.gba',
  '391 X-Men-Reign of Apocalypse.gba',
  '392 X-Men-The Official Game.gba',
  '393 xXx.gba',
  '394 Yoshi Topsy Turvy.gba',
  '395 Yu Yu Hakusho Spirit DetETCive.gba',
  '396 Yu Yu Hakusho Tournament Tactics.gba',
  '397 Yu-Gi-Oh Destiny Board Traveler.gba',
  '398 Yu-Gi-Oh! 7 Trials to Glory.gba',
  '399 Yu-Gi-Oh! Dungeondice Monsters.gba',
  '400 Yu-Gi-Oh! GX Duel Academy.gba',
  '401 Yu-Gi-Oh! The Sacred Cards.gba',
  '402 Yu-Gi-Oh! Ultimate Masters 2006.gba',
  '403 Yu-gi-oh!-reshef of destruction.gba',
  '404 Yu-gi-oh!-world championship tournament 2004.gba',
  '405 Yu-gi-oh!-worldwide edition - stairway to the destined duel.gba',
  '406 Yu-Gi-Oh-The Eternal Duelist Soul.gba',
  '407 Zone of the enders-the fist of mars.gba',
  '408 Puyo Pop.gba',
  '409 Puyo Pop Fever.gba',
  '410 Tactics Ogre-The Knight of Lodis.gba',
  '411 Phantasy Star Collection.gba',
  '412 Bubble Bobble-Old & New.gba',
  '413 Shaman King-Master of Spirits.gba',
  '414 Arthur and the Invisibles.gba',
  '415 Namco Museum.gba',
  '416 Shining Force-Resurrection of the Dark Dragon.gba',
  '417 BMX Trick Racer.gba',
  '418 Hunter X Hunter-Minna Tomodachi Daisakusen!!.gba',
  '419 Riviera-The Promised Land.gba',
  "420 Snap Kid's.gba",
  '421 Tales of Phantasia.gba',
  '422 Prince of Persia.gba',
  '423 Shonen Jumps One Piece.gba',
  '424 Pokemon ChaosBlack Version.gba',
  '425 Pokemon Crystal Sharos.gba',
  '426 Pokemon Dark Cry Version.gba',
  '427 Pokemon Blue Sea Edition.gba',
  "428 Pokemon Lugia's Ocean Version.gba",
  '429 Pokemon ShinyGold Version.gba',
  '430 Avatar 2.gba',
  '431 Backtrack.gba',
  '432 Backyard Baseball 2006.gba',
  '433 Backyard Baseball.gba',
  '434 Backyard Basketball.gba',
  '435 Backyard hockey.gba',
  '436 Backyard Sports Baseball 2007.gba',
  '437 Backyard Sports Basketball 2007.gba',
  '438 Backyard Sports Basketball.gba',
  '440 Barbie and the Magic of Pegasus.gba',
  '441 Barbie Groovy Games.gba',
  '442 Barbie Horse Adventures.gba',
  '443 Barbie in the 12 Dancing Princesses.gba',
  '444 Barbie The Princess And The Pauper.gba',
  '445 Beyblade G-Revolution.gba',
  '446 Bit Generations-Boundish.gba',
  '447 Board Game Classics.gba',
  '448 Bomberman Tournament.gba',
  '449 Bookworm.gba',
  '450 Boulder Dash EX.gba',
  '451 Bratz Babyz.gba',
  '452 Bratz-The Movie.gba',
  '453 Bratz.gba',
  '454 Breath of fire 2.gba',
  '455 Breath of fire.gba',
  '456 Robotech-The Macross Saga.gba',
  '457 Cabbage Patch Kids The Patch Puppy Rescue.gba',
  '459 Camp Lazlo-Leaky Lake Game.gba',
  '460 Candy Land, Chutes and Ladders, Memory Game.gba',
  '461 Care Bears-The Care Quest.gba',
  '462 Carrera Power Slide.gba',
  '463 Cartoon Network Block Party.gba',
  '464 Cartoon Network-Speedway.gba',
  '465 Casper.gba',
  '466 Catz.gba',
  '467 Chessmaster.gba',
  '468 Chu Chu Rocket.gba',
  '469 Cocoto Kart Racer.gba',
  '470 Colin McRae Rally 2.0.gba',
  '471 Comix Zone.gba',
  '472 Connect Four.Perfection.Trouble.gba',
  '473 Sega Arcade Gallery.gba',
  '474 Crazy Frog Racer.gba',
  '475 Creatures.gba',
  "476 Cruis'n Velocity.gba",
  '478 Danny Phantom-The Ultimate Enemy.gba',
  '479 Danny Phantom-Urban Jungle.gba',
  '480 Daredevil.gba',
  '481 David Beckham Soccer.gba',
  '482 Davis Cup.gba',
  '483 Deal or No Deal.gba',
  '484 Denki Blocks.gba',
  '485 Digimon Battle Spirit 1.gba',
  '486 Digimon Battle Spirit 2.gba',
  "487 Disney's Aladdin.gba",
  "488 Disney's Magical Quest 2.gba",
  "489 Disney's Magical Quest Starring Mickey and Minnie.gba",
  '490 Dora the Explorer Super Star Adventures.gba',
  '491 Dora The Explorer-Super Spies.gba',
  "492 Dora the Explorer-The Search for Pirate Pig's Treasure.gba",
  "493 Dora's World Adventure.gba",
  '494 Downforce.gba',
  "495 Dr. Seuss'-The Cat in the Hat.gba",
  "496 Dragon's Rock.gba",
  '497 Drake and Josh.gba',
  '498 Driven.gba',
  '499 Droopys Tennis Open.gba',
  '500 E.T. The Extra-Terrestrial.gba',
  '501 Ed. Edd N Eddy-Jawbreakers!.gba',
  '502 Elf Bowling 1 & 2.gba',
  '503 ESPN International Winter Sports 2002.gba',
  '504 ESPN Winter X-Games Snowboarding 2002.gba',
  '505 European Super League.gba',
  '506 Extreme Ghostbusters-Code ETCo-1.gba',
  '507 F-Zero-Maximum Velocity.gba',
  '508 F1 2002.gba',
  '509 F24 Stealth Fighter.gba',
  '510 Fairly Odd Parents Breakin Da Rules.gba',
  '511 Fairly Odd Parents Clash With The Anti-Wold.gba',
  '512 Fairly Odd Parents Enter The Cleft.gba',
  '513 Fairly Odd Parents!. The-Shadow Showdown.gba',
  '514 Family Feud.gba',
  '515 FIFA 2003.gba',
  '516 FightBox.gba',
  '517 Final Fight One.gba',
  '518 Finding Nemo-The Continuing Adventures.gba',
  "520 Foster's Home for Imaginary Friends.gba",
  "521 Franklin's Great Adventure.gba",
  '522 Freestyle scooter.gba',
  '523 Froggers Adventures-Temple of the Frog.gba',
  '524 Games Explosion.gba',
  '525 Go! Go! Beckham! Adventure On Soccer Island.gba',
  '526 Gradius Advance.gba',
  '527 Gremlins-Stripe vs Gizmo.gba',
  '528 GT Championship.gba',
  '530 Gundam Seed-Battle Assault.gba',
  '531 Hello Kitty-Happy Party Pals.gba',
  '532 Hey Arnold! The Movie.gba',
  '533 High Heat Baseball 2002.gba',
  '534 High Heat Major League Baseball 2003.gba',
  '535 Hot Potato.gba',
  '536 Hot Wheels-All Out.gba',
  '537 Ice Age.gba',
  '538 Inspector Gadget Racing.gba',
  '539 InspETCor Gadget-Advance Mission.gba',
  '540 International Karate Advanced.gba',
  '541 Jackie Chan Adventures-Legend Of The Dark Hand.gba',
  '542 Jazz Jackrabbit.gba',
  '543 Jimmy Neutron-Boy Genius.gba',
  '544 Jimmy Neutron-Jet Fusion.gba',
  '545 Jurassic park III - park builder.gba',
  '546 Kao the Kangaroo.gba',
  '547 Ker Plunk!-Toss Across-Tip It.gba',
  '548 Killer 3D Pool.gba',
  '549 Klonoa 1-Empire of Dreams.gba',
  '550 Klonoa 2-Dream Champ Tournament.gba',
  '551 Konami CollETCors Series-Arcade Advanced.gba',
  '552 Konami Krazy Racers.gba',
  '553 Kong-King of Atlantis.gba',
  '554 Lady Sia.gba',
  '555 LEGO Bionicle Matoran Adventures.gba',
  '556 Lizzie McGuire.gba',
  '557 Lode Runner.gba',
  '558 Magical Quest Starring Mickey & Minnie.gba',
  '559 Maniac Racer Advance.gba',
  '560 Marble Madness, Klax.gba',
  '561 March Of The Penguins.gba',
  '562 Mary Kate and Ashley Girls Night Out.gba',
  '563 Mary-Kate and Ashley-Sweet 16.gba',
  "564 Mat Hoffman's Pro BMX 2.gba",
  '565 Men in Black-The Series.gba',
  '566 Micro Machines.gba',
  '567 Midnight Club Street Racing.gba',
  '568 Midways Greatest Arcade Hits.gba',
  '569 Mike Tysons Boxing.gba',
  '570 Mission Impossible Operation Surma.gba',
  '571 Monopoly.gba',
  '572 Monster Trucks Mayhem.gba',
  '573 Monsters Inc..gba',
  '574 Moto GP.gba',
  '575 Mr. Driller 2.gba',
  '576 MX 2K2 Featuring Ricky Carmichael.gba',
  '577 My Little Pony-Crystal Princess.gba',
  '578 My Pet Hotel.gba',
  '579 The  Bible Game.gba',
  '580 Nancy Drew-Message in a Haunted Mansion.gba',
  '581 NASCAR Heat 2002.gba',
  '582 Need For Speed Porsche Unleashed.gba',
  '583 Need For Speed Porsche.gba',
  '584 NFL Blitz 2002.gba',
  '585 Nicktoons Racing.gba',
  '586 Nicktoons-Attack of the Toybots.gba',
  '587 Ninja 5-0.gba',
  '588 Noddy A day in Toyland.gba',
  '589 Sega Rally Championship.gba',
  '590 Sega Smash Pack.gba',
  '591 Silent Scope.gba',
  '592 Peter Pan-The Movie.gba',
  '593 Pferd & Pony-Mein Pferdehof.gba',
  '594 Phalanx.gba',
  '595 Pinball Advance.gba',
  '596 Pinball Challenge Deluxe.gba',
  '597 Pinball Tycoon.gba',
  '598 Pinky Monkey Town.gba',
  '599 Planet Monsters.gba',
  '600 Planet Of The Apes.gba',
  '601 Pocket Professor-Kwik Notes Vol.one.gba',
  '602 Polly Pocket-Super Splash Island.gba',
  '603 Popeye-Rush for Spinach.gba',
  '604 Postman Pat and the Greendale Rocket.gba',
  '605 Power Rangers-Dino Thunder.gba',
  '606 Power Rangers-Ninja Storm.gba',
  '607 Power Rangers-S.P.D..gba',
  '608 Power Rangers-Time Force.gba',
  '609 Power Rangers-Wild Force.gba',
  '610 Prehistorik Man.gba',
  '611 Princess Natasha.gba',
  '612 Puppy Luv-Spa and Resort.gba',
  '613 Racing Fever.gba',
  '614 Rampage Puzzle Attack.gba',
  '616 Razor Freestyle Scooter.gba',
  '617 Ready 2 Rumble-Round 2.gba',
  '618 Rebelsta-Tactical Command.gba',
  '619 Rescue Heroes Billy Blazes.gba',
  '620 River City Ransom EX.gba',
  '621 Road Rash Jailbreak.gba',
  '622 Robot Wars-Advanced Destruction.gba',
  "623 Rock'em Sock'em Robots.gba",
  '624 Rocket Power Dream Scheme.gba',
  '625 Roland Garros 2002-Next Generation Tennis.gba',
  '626 Rugrats-Castle Capers.gba',
  '627 Rugrats-Go Wild.gba',
  '628 Rugrats-I Gotta Go Party.gba',
  '629 Sabrina The Teenage Witch-Potion Commotion.gba',
  '630 Salt Lake 2002.gba',
  '631 Scooby Doo and the Cyber Chase.gba',
  '632 Sea Trader-The Rise of Taipan.gba',
  '633 Sheep.gba',
  '634 Shrek Hassle At The Castle.gba',
  '635 Sim City 2000.gba',
  '636 Simple 2960 Tomodachi Series Vol. 1 - The Table Game Collection.gba',
  '637 Sitting Ducks.gba',
  '638 Sky Dancers They Magically Fly.gba',
  '639 Snood.gba',
  '640 Sonic the Hedgehog Genesis.gba',
  '642 Speedball 2.gba',
  '643 Spirit-Stallion Of The Cimarron.gba',
  '644 Sponge Bob Square Pants-SuperSponge.gba',
  '645 Spongebob Squarepants And Friends Unite!.gba',
  '646 SpongeBob SquarePants and Friends-Battle for Volcano Island.gba',
  '647 SpongeBob SquarePants Lights Camera Pants.gba',
  "648 SpongeBob's Atlantis SquarePantis.gba",
  '649 Sports Illustrated For Kids-Baseball.gba',
  '650 Sports Illustrated For Kids-Football.gba',
  '651 Spy Hunter, Super Sprint.gba',
  '652 Spy Kids Challenger.gba',
  '653 Stadium Games.gba',
  '654 Starsky & Hutch.gba',
  '655 Strawberry Shortcake Sweet Dreams.gba',
  '656 Strawberry Shortcake-Summertime Adventure.gba',
  '657 Street Jam Basketball.gba',
  '658 Stuntman.gba',
  '659 Super Army War.gba',
  '660 Super Black Bass Advance.gba',
  '661 Super Breakout, Millipede, Lunar Lander.gba',
  '662 Super Bubble Pop.gba',
  '663 Super Bust-A-Move.gba',
  '664 Super Dodge Ball Advance.gba',
  "665 Super Ghouls'n Ghosts.gba",
  '666 Super Hornet FA 18F.gba',
  '668 Ten Pin Alley 2.gba',
  '670 The Bee Game.gba',
  '671 The Flintstones-Big Trouble in Bedrock.gba',
  '673 The Land Before Time.gba',
  '674 The Mummy.gba',
  '675 The Powerpuff Girls-Mojo Jojo A-Go-Go.gba',
  '676 The Revenge Of The Smurfs.gba',
  '677 The Ripping Friends.gba',
  '678 The Scorpion King-Sword of Osiris.gba',
  '679 The Wild Thornberrys-Chimp Chase.gba',
  '680 Three Stooges.gba',
  '681 Tiny Toon Adventures-Busters Bad Dream.gba',
  '682 Tiny Toon Adventures-Wacky Stacker.gba',
  '683 Tokyo Xtreme Racer Advance.gba',
  '684 Tom and Jerry in Infurnal Escape.gba',
  '685 Tonka On the Job.gba',
  '686 Top Gun Firestorm Advance.gba',
  '687 Total Soccer Manager.gba',
  '688 Turbo Turtle Adventure.gba',
  '689 Tweety & The Magic Gems.gba',
  '690 Ultimate Beach Soccer.gba',
  '691 Ultimate Card Games.gba',
  '692 Ultimate Puzzle Games.gba',
  '693 Unfabulous.gba',
  '694 V-Rally 3.gba',
  '695 Van Helsing.gba',
  '696 VeggieTales-LarryBoy and the Bad Apple.gba',
  '697 VIP.gba',
  '698 Virtual Kasparov.gba',
  "699 Winnie the Pooh's-Rumbly Tumbly Adventure.gba",
  '700 Worms World Party 1.gba',
  '701 Worms World Party 2.gba',
  '702 WTA Tour Tennis.gba',
  '703 WWE Road To Wrestlemania X8.gba',
  '704 WWE Survivor Series.gba',
  '705 WWF-Road to Wrestlemania.gba',
  '706 XS Moto.gba',
  '707 Zidane Football Generation 2002.gba',
  '708 ZooCube.gba',
  "709 Tim Burton's The Nightmare Before Christmas.gba",
  '710 TOCA World Touring Cars.gba',
  '711 Turok Evolution.gba',
  "712 Wade Hixton's Counter Punch.gba",
  '713 Zatchbell!-Electric Arena.gba',
  '714 Zoids Legacy.gba',
  '715 Zooo.gba',
  '716 All Grown Up! -Express Yourself.gba',
  '717 Defender of the Crown.gba',
  '718 Defender-For All Mankind.gba',
  '719 Dual Blades.gba',
  '720 Dungeons & Dragons-Eye of the Beholder.gba',
  '721 F-14 Tomcat.gba',
  '722 Flashback Legends.gba',
  '723 Fortress.gba',
  '724 Galidor-Defenders of the Outer Dimension.gba',
  '725 Gauntlet, Rampart.gba',
  '726 Heidi-The Game.gba',
  '727 Inspector Gadget-Advance Mission.gba',
  '728 Iridion 3D.gba',
  "729 Konami Collector's Series.gba",
  '730 Kurukuru Kururin.gba',
  '731 LEGO Island -Xtreme Stunts.gba',
  '732 Life, Yahtzee, Payday.gba',
  '733 Metal Max 2 Kai.gba',
  "734 Midway's Greatest Arcade Hits.gba",
  '735 Motocross Challenge.gba',
  '736 Mucha Lucha!-Mascaritas of the Lost Code.gba',
  '737 NFL Blitz 2003.gba',
  '738 Paperboy, Rampage.gba',
  '739 Pinky and the Brain-The Masterplan.gba',
  '740 Rebelstar-Tactical Command.gba',
  '741 R-Type III-The Third Lightning.gba',
  '742 Soccer Kid.gba',
  '743 Spirits & Spells.gba',
  '744 Tennis Masters Series 2003.gba',
  "745 Texas Hold'em Poker.gba",
  '746 Ultimate Brain Games.gba',
  '747 Zoey 101.gba',
  '748 A Sound of Thunder.gba',
  '749 Altered Beast-Guardian of the Realms.gba',
  '750 Army Men-Turf Wars.gba',
  "751 Baldur's Gate-Dark Alliance.gba",
  '752 Battle B-Daman-Fire Spirits.gba',
  '753 Bionicle.gba',
  '754 Car Battler Joe.gba',
  '755 Ace Combat Adv.gba',
  '756 Ace Combat Advance.gba',
  '757 Ace Lightning.gba',
  '758 Action Man-Robot Attack.gba',
  '759 Advance Wars.gba',
  '760 Max Payne.gba',
  '761 Naruto - konoha senki.gba',
  '762 Naruto Ninja Council 1.gba',
  '763 Naruto Ninja Council 2.gba',
  '764 Naruto RPG-Uketsugareshi Hi no Ishi.gba',
  '765 Lunar Legend.gba',
  '766 Advance Wars 2.gba',
  '767 Pac-Man World.gba',
  '768 Pac-Man Collection.gba',
  '769 Pac-Man Pinball Advance.gba',
  '770 Pac-Man World 2.gba',
  '771 2 in 1-Looney Tunes Double Pack.gba',
  '772 2 in 1-Matchbox Missions.gba',
  '773 Alien Hominid.gba',
  '774 Arthur and the Minimoys.gba',
  '775 Ballistic Ecks Vs Sever 2.gba',
  '776 Banjo Pilot.gba',
  '778 Batman Begins.gba',
  '779 Big Mutha Truckers.gba',
  '780 Bit Generations-Dotstream.gba',
  '781 Black Belt Challenge.gba',
  '782 Blackthorne.gba',
  '783 Boktai 2-Solar Boy Django.gba',
  '784 Buffy The Vampire Slayer-Return of the Dark King.gba',
  '785 Butt Ugly Martians BKM Battles.gba',
  "786 Caesar's Palace Advance.gba",
  '787 Cars Mater-National.gba',
  '788 Cars.gba',
  '789 Castleween.gba',
  '790 Centipede. Breakout. Warlords.gba',
  '791 Chicken Shoot.gba',
  '792 Chocobo Land-Game de Dice.gba',
  '793 ChuChu Rocket!.gba',
  '794 Cocoto Platform Jumper.gba',
  '795 Codename-Kids Next Door.gba',
  '796 Combat Choro Q.gba',
  '797 Crazy Chase.gba',
  "798 Cubix-Robots for Everyone-Clash'n Bash.gba",
  '799 Defender.gba',
  '800 Demon Drive Time to Burn Rubber.gba',
  "801 Dexter's Laboratory-Deesaster Strikes.gba",
  "803 Disney's Kim Possible 2.gba",
  "804 Disney's Thats so Raven 2.gba",
  '806 DOOM.gba',
  '807 Doraemon Midori No Wakusei.gba',
  '808 Dr Seuss Green-Eggs and Ham.gba',
  '809 Drill Dozer.gba',
  '810 Duke Nukem Advance.gba',
  '811 Enchanted-Once Upon Andalasia.gba',
  '812 Fushigi no Kuni no Alice.gba',
  '813 Garfield and His Nine Lives.gba',
  '814 Garfield The Search For Pooky.gba',
  '815 GBADev 2004Mbit Compeition.gba',
  '816 Godzilla - Domination!.gba',
  '817 Hachimon.gba',
  '818 Hi Hi Puffy AmiYumi-Kaznapped.gba',
  '819 Hugo-The Evil Mirror.gba',
  '821 Iron Kid.gba',
  "822 It's Mr Pants.gba",
  '823 Jet Grind Radio.gba',
  '824 Jimmy Neutron vs Jimmy Negatron.gba',
  '825 Jimmy Neutron-Attack of the Twonkies.gba',
  '826 Kelly Slaters Pro Surfer.gba',
  '827 Kid Paddle.gba',
  '829 Klonoa Heroes-Densetsu no Star Medal.gba',
  '830 Legendz-Buhwarhaneun Siryeonyi Seom.gba',
  "831 Let's Ride!-Sunshine Stables.gba",
  '832 Lets Ride Dreamer.gba',
  '833 Little Einstein.gba',
  '834 Lucky Luke-Wanted！.gba',
  '835 Madagascar.gba',
  '836 Mahou Sensei Negima Private Lesson 2.gba',
  '837 Manic Miner.gba',
  '838 Matchbox Crosstown Heroes.gba',
  '839 Maya the Bee.gba',
  '840 Mazes of Fate.gba',
  '841 Monster Force.gba',
  '842 Monster Truck Madness.gba',
  '843 Moorhen 3 Chicken Chase.gba',
  '844 Motoracer Advance.gba',
  '845 Mr. Nutz.gba',
  '846 Need for Speed Carbon-Own the City.gba',
  '847 Ozzy and Drix.gba',
  '848 Paard & Pony-Mijn Manege.gba',
  '849 Pinball Tycoon.gba',
  '850 Pinobee-Wings of Adventure.gba',
  '851 Pitfall-The Mayan Adventure.gba',
  '852 Pixeline in Pixieland.gba',
  '853 Pocket Music.gba',
  '854 Pocky & Rocky with Becky.gba',
  '855 Pokemon Arcoiris Version.gba',
  '856 Pokemon Frego Retern.gba',
  '857 Pokemon Naranja Version.gba',
  '858 Pokemon Perla Version.gba',
  '859 Pokemon Quartz Version.gba',
  '860 Qwak.gba',
  '861 Rebelstar Tactical Command.gba',
  '862 Reign of Fire.gba',
  '863 Robot Wars-Extreme Destruction.gba',
  '864 Rocket Power-Beach Bandits.gba',
  '866 Sabre Wulf.gba',
  '867 Scooby Doo-Mystery Mayhem.gba',
  '868 Scooby Doo-The Motion Picture.gba',
  '869 Scurge Hive.gba',
  '870 Serious Sam Advance.gba',
  "871 Shamu's Deep Sea Adventures.gba",
  '872 Shifting Gears-Road Trip.gba',
  '873 Sigma Star Saga.gba',
  '874 Silent Hill Play Novel.gba',
  '875 Snood 2 On Vacation.gba',
  '876 Spirits and Spells.gba',
  '877 Spy Muppets-License to.gba',
  '879 Super Dropzone.gba',
  '880 Super Duper Sumos.gba',
  '881 Sutekina Obentou.gba',
  '882 The Berenstain Bears.gba',
  '883 The Land Before Time Into the Mysterious Beyond.gba',
  '884 The Lost Vikings.gba',
  '885 The Polar Express.gba',
  '886 The Proud Family.gba',
  '887 The Tower SP.gba',
  '888 Titeuf Mega Compet.gba',
  '890 Tootuff-The Gagmachine.gba',
  '891 Ultimate Arcade Games.gba',
  '892 Urban Yeti.gba',
  '893 Whac-a-mole.gba',
  '894 Who Wants to be a Millionaire.gba',
  '895 Woody Woodpecker In Crazy Castle 5.gba',
  '896 Aero The Acrobat.gba',
  '897 Agassi Tennis Generation.gba',
  '898 Agent Hugo Roborumble.gba',
  '899 Airforce Delta Storm.gba',
  '900 Alienators-Evolution Continues.gba',
  '901 All-Star Baseball.gba',
  '902 An American Tail-Fievels Gold Rush.gba',
  '903 Animal Snap-Rescue them  by.gba',
  '904 Antz Extreme Racing.gba',
  '905 Arctic Tale.gba',
  '906 Army Men Advance.gba',
  '907 Army Men-Operation Green.gba',
  '908 Around The World In  Days.gba',
  '909 Atari Anniversary Advance.gba',
  '910 Atlantis-The Lost Empire.gba',
  '911 ATV Thunder Ridge Riders.gba',
  '912 ATV-Quad Power Racing.gba',
  '913 Sudoku.gba',
  '914 Anguna.gba',
  '915 Super Move Quest.gba',
  '916 Tiger Resecu.gba',
  '917 Tringo.gba',
  '918 Win Or Lose.gba',
  '919 Zippy Froger.gba',
  "920 Archer Maclean's D Pool.gba",
  '921 Tang Tang.gba',
  '922 Box Puzzle.gba',
  '923 Hanoic Tower.gba',
  '924 Happy Checkers.gba',
  '925 Hero Legend.gba',
  '926 Hide and Seek.gba',
  '927 Hot Drop.gba',
  '928 Jewel Fever.gba',
  '929 Jewel Master.gba',
  '930 Lightning Plan.gba',
  '931 Manic Troll.gba',
  '932 Mr Onion.gba',
  '933 On N Off.gba',
  '934 Operation Armored Liberty.gba',
  '935 Pinball Fish.gba',
  '936 Plumber.gba',
  '937 Pool Pro.gba',
  '938 Pop Ball.gba',
  '939 Quick Move.gba',
  '940 Rapid Stream.gba',
  '941 Rolling Cube.gba',
  "942 Steven Gerrard's Total Soccer.gba",
  '943 Bubble Blaster.gba',
  '944 Bump Bomb.gba',
  '945 Dragon.gba',
  '946 Fire Fighter.gba',
  '947 Super Collapse! II.gba',
  '948 Busy Bong.gba',
  'Pokemon Glazed.gba',
]
